words = {
  "Животные": {
    "wolf": "волк",
    "fox": "лиса",
    "bear": "медведь",
    "tiger": "тигр",
    "lion": "лев",
    "elephant": "слон",
    "monkey": "обезьяна",
    "camel": "верблюд",
    "rabbit": "кролик",
    "squirrel": "белка",
    "zebra": "зебра",
    "kangaroo": "кенгуру",
    "crocodile": "крокодил",
    "deer": "олень",
    "lynx": "рысь",
    "cheetah": "гепард",
    "raccoon": "енот",
    "giraffe": "жираф",
    "hedgehog": "еж",
    "anteater": "муравьед",
    "domestic animals": "домашние животные",
    "cow": "корова",
    "bull": "бык",
    "horse": "лошадь",
    "guinea pig": "морская свинка",
    "wild animal": "дикое животное"
  },
  "Еда": {
    "pear": "груша",
    "strawberry": "клубника",
    "grapes": "виноград",
    "carrot": "морковь",
    "cucumber": "огурец",
    "cabbage ": "капуста",
    "ham": "ветчина",
    "beef": "говядина",
    "pork": "свинина",
    "salmon": "семга",
    "shrimps": "креветки",
    "trout ": "форель",
    "turkey": "индейка",
    "goose": "гусь",
    "duck": "утка",
    "milkshake": "молочный коктейль",
    "soda": "газировка",
    "juice": "сок",
    "cocoa ": "какао",
    "coffee ": "кофе",
    "bread": "хлеб",
    "bun": "булка",
    "mustard": "горчица",
    "sour cream": "сметана",
    "pearl barley": "перловка"
  },
  "85 основных глаголов": {
    "choose": "выбирать",
    "draw": "рисовать",
    "catch": "ловить",
    "cover": "покрывать",
    "eat ": "есть(еду)",
    "produce": "производить",
    "support": "поддерживать",
    "agree": "соглашаться",
    "receive": "получать",
    "break": "ломать",
    "carry": "везти",
    "develop": "развивать",
    "hope": "надеяться",
    "explain": "объяснять",
    "return": "возвращаться",
    "decide": "решать",
    "sell": "продавать",
    "pass": "миновать",
    "raise": "поднимать",
    "kill": "убивать",
    "reach": "достигать",
    "cut": "резать",
    "fall": "падать",
    "build": "строить",
    "send": "посылать",
    "buy": "покупать",
    "appear": "появляться",
    "consider": "считать",
    "remember": "помнить",
    "teach": "учить",
    "win": "побеждать",
    "walk": "идти",
    "grow": "расти",
    "spend": "тратить",
    "read": "читать",
    "speak": "говорить",
    "create": "создавать",
    "stop": "останавливать",
    "follow": "следовать",
    "watch": "смотреть",
    "understand": "понимать",
    "change": "менять",
    "learn": "учить",
    "continue": "продолжать",
    "meet": "встречать",
    "pay": "платить",
    "lose": "терять",
    "stand": "стоять",
    "sit": "сидеть",
    "write": "писать",
    "happen": "случаться",
    "believe": "верить",
    "live": "жить",
    "move": "двигаться",
    "run": "бежать",
    "play": "играть",
    "hear": "слышать",
    "help": "помогать",
    "seem": "казаться",
    "begin": "начинать",
    "keep": "хранить",
    "put": "класть",
    "leave": "оставлять",
    "become": "становиться",
    "feel": "чувствовать",
    "need": "нуждаться",
    "ask": "просить/спрашивать",
    "try": "пытаться",
    "call": "звать/звонить",
    "work": "работать",
    "tell": "рассказывать",
    "give": "давать",
    "find": "находить",
    "want": "хотеть",
    "use": "использовать",
    "see": "видеть",
    "take": "брать",
    "think": "думать",
    "know": "знать",
    "make": "делать",
    "get": "получать",
    "go": "идти",
    "say": "говорить",
    "do": "делать",
    "have": "иметь",
    "be": "быть",
  },
  "Королевский набор": {
    "dominions": "владения",
    "king": "король",
    "courtiers": "придворные",
    "empress": "императрица",
    "nobles": "дворяне",
    "queen": "королева",
    "emperor": "император",
    "troop": "войска",
    "battlement": "зубчатая стена",
    "fortress": "крепость",
    "castle": "замок",
    "kingdom": "королевство",
    "slave": "раб",
    "servant": "слуга",
    "tower": "башня",
    "valor": "доблесть",
    "crown": "корона",
    "duke": "герцог",
    "duchesses": "герцогиня",
    "regal": "царский"
  },
  "Базовый бизнес-словарь": {
    "Advantage": "превосходство",
    "Advertisement": "реклама",
    "Advice": "совет",
    "Brand": "марка",
    "Competition": "конкуренция",
    "Costs": "расходы",
    "Creditor": "кредитор",
    "Debt": "долг",
    "Deadline": "крайний срок",
    "Decision": "решение",
    "Employee": "сотрудник",
    "Enquiry": "запрос",
    "Estimate": "оценка",
    "Experience": "опыт",
    "Facilities": "средства",
    "Feedback": "обратная связь",
    "Goal": "цель",
    "Improvement": "улучшение",
    "Increase": "увеличение",
    "Knowledge": "знание",
    "Market": "рынок",
    "Offer": "предложение",
    "Penalty": "штраф",
    "Permission": "разрешение",
    "Possibility": "возможность",
    "Profit": "прибыль",
    "Refund": "возврат",
    "Reminder": "напоминание",
    "Responsibility": "ответственность",
    "Retailer": "розничный торговец",
    "Salary": "зарплата",
    "Schedule": "график",
    "Suggestion": "предложение",
    "Wholesaler": "оптовик",
    "Turnover": "оборот",
    "Success ": "успех",
  },
  "Путешествия 1": {
    "traveling": "путешествие",
    "be fond of traveling": "любить путешествовать",
    "journey": "длительное путешествие",
    "school trip": "экскурсия",
    "two-day trip": "двухдневная поездка",
    "tour": "поездка/ тур",
    "package tour": "путешествие по тур. путевке",
    "cruise": "круиз",
    "flight": "полет",
    "hitch-hike": "путешествие автостопом",
    "travel agency": "туристическое агентство",
    "destination": "место назначения",
    "luggage": "багаж",
    "suitcase": "чемодан",
    "rucksack": "рюкзак",
    "porter": "носильщик",
    "information desk": "справочное бюро",
    "to arrive": "прибывать",
    "to depart": "отправляться",
    "boarding": "посадка",
    "customs": "таможня",
    "passport control": "паспортный контроль",
    "excess weight": "превышение веса",
    "railway station": "ж/д станция",
    "carriage": "вагон",
    "make a reservation": "забронировать место"
  }
}
