words = {
  "Животные": {
    "wolf": "волк",
    "fox": "лиса",
    "bear": "медведь",
    "tiger": "тигр",
    "lion": "лев",
    "elephant": "слон",
    "monkey": "обезьяна",
    "camel": "верблюд",
    "rabbit": "кролик",
    "squirrel": "белка",
    "zebra": "зебра",
    "kangaroo": "кенгуру",
    "crocodile": "крокодил",
    "deer": "олень",
    "lynx": "рысь",
    "cheetah": "гепард",
    "raccoon": "енот",
    "giraffe": "жираф",
    "hedgehog": "еж",
    "anteater": "муравьед",
    "domestic animals": "домашние животные",
    "cow": "корова",
    "bull": "бык",
    "horse": "лошадь",
    "guinea pig": "морская свинка",
    "wild animal": "дикое животное"
  },
  "Еда": {
    "pear": "груша",
    "strawberry": "клубника",
    "grapes": "виноград",
    "carrot": "морковь",
    "cucumber": "огурец",
    "cabbage ": "капуста",
    "ham": "ветчина",
    "beef": "говядина",
    "pork": "свинина",
    "salmon": "семга",
    "shrimps": "креветки",
    "trout ": "форель",
    "turkey": "индейка",
    "goose": "гусь",
    "duck": "утка",
    "milkshake": "молочный коктейль",
    "soda": "газировка",
    "juice": "сок",
    "cocoa ": "какао",
    "coffee ": "кофе",
    "bread": "хлеб",
    "bun": "булка",
    "mustard": "горчица",
    "sour cream": "сметана",
    "pearl barley": "перловка"
  },
  "Основные глаголы": {
    "choose": "выбирать",
    "draw": "рисовать",
    "catch": "ловить",
    "cover": "покрывать",
    "eat ": "есть еду",
    "produce": "производить",
    "support": "поддерживать",
    "agree": "соглашаться",
    "receive": "получать",
    "break": "ломать",
    "carry": "везти",
    "develop": "развивать",
    "hope": "надеяться",
    "explain": "объяснять",
    "return": "возвращаться",
    "decide": "решать",
    "sell": "продавать",
    "pass": "миновать",
    "raise": "поднимать",
    "kill": "убивать",
    "reach": "достигать",
    "cut": "резать",
    "fall": "падать",
    "build": "строить",
    "send": "посылать",
    "buy": "покупать",
    "appear": "появляться",
    "consider": "считать",
    "remember": "помнить",
    "teach": "учить",
    "win": "побеждать",
    "walk": "идти",
    "grow": "расти",
    "spend": "тратить",
    "read": "читать",
    "speak": "говорить",
    "create": "создавать",
    "stop": "останавливать",
    "follow": "следовать",
    "watch": "смотреть",
    "understand": "понимать",
    "change": "менять",
    "learn": "учить",
    "continue": "продолжать",
    "meet": "встречать",
    "pay": "платить",
    "lose": "терять",
    "stand": "стоять",
    "sit": "сидеть",
    "write": "писать",
    "happen": "случаться",
    "believe": "верить",
    "live": "жить",
    "move": "двигаться",
    "run": "бежать",
    "play": "играть",
    "hear": "слышать",
    "help": "помогать",
    "seem": "казаться",
    "begin": "начинать",
    "keep": "хранить",
    "put": "класть",
    "leave": "оставлять",
    "become": "становиться",
    "feel": "чувствовать",
    "need": "нуждаться",
    "ask": "просить или спрашивать",
    "try": "пытаться",
    "call": "звать или звонить",
    "work": "работать",
    "tell": "рассказывать",
    "give": "давать",
    "find": "находить",
    "want": "хотеть",
    "use": "использовать",
    "see": "видеть",
    "take": "брать",
    "think": "думать",
    "know": "знать",
    "make": "делать",
    "get": "получать",
    "go": "идти",
    "say": "говорить",
    "do": "делать",
    "have": "иметь",
    "be": "быть",
  },
  "Королевский": {
    "dom+inions": "владения",
    "king": "король",
    "courtiers": "придворные",
    "empress": "императрица",
    "nobles": "дворяне",
    "queen": "королева",
    "emperor": "император",
    "troop": "войска",
    "battlement": "зубчатая стена",
    "fortress": "крепость",
    "castle": "замок",
    "kingdom": "королевство",
    "slave": "раб",
    "servant": "слуга",
    "tower": "башня",
    "valor": "доблесть",
    "crown": "корона",
    "duke": "герцог",
    "duchesses": "герцогиня",
    "regal": "царский"
  },
  "Бизнес": {
    "advantage": "превосходство",
    "advertisement": "реклама",
    "advice": "совет",
    "brand": "марка",
    "competition": "конкуренция",
    "costs": "расходы",
    "creditor": "кредитор",
    "debt": "долг",
    "deadline": "крайний срок",
    "decision": "решение",
    "employe+e": "сотрудник",
    "enq+uiry": "запрос",
    "estimate": "оценка",
    "experience": "опыт",
    "facilities": "средства",
    "feedb+ack": "обратная связь",
    "goal": "цель",
    "improvement": "улучшение",
    "+increase": "увеличение",
    "kn+owledge": "знание",
    "market": "рынок",
    "offer": "предложение",
    "pen+alty": "штраф",
    "permission": "разрешение",
    "possib+ility": "возможность",
    "profit": "прибыль",
    "refund": "возврат",
    "reminder": "напоминание",
    "responsibility": "ответственность",
    "retailer": "розничный торговец",
    "salary": "зарплата",
    "schedule": "график",
    "suggestion": "предложение",
    "wholesaler": "оптовик",
    "turnover": "оборот",
    "success ": "успех",
  },
  "Путешествия 1": {
    "traveling": "путешествие",
    "be fond of traveling": "любить путешествовать",
    "journey": "длительное путешествие",
    "school trip": "экск+урсия",
    "two-day trip": "двухдневная поездка",
    "tour": "поездка или тур",
    "package tour": "путешествие по тур. путевке",
    "cruise": "круиз",
    "flight": "полет",
    "hitch-hike": "путешествие автостопом",
    "travel agency": "туристическое агентство",
    "destination": "место назначения",
    "luggage": "багаж",
    "suitcase": "чемодан",
    "rucksack": "рюкзак",
    "porter": "носильщик",
    "information desk": "справочное бюро",
    "to arrive": "прибывать",
    "to depart": "отправляться",
    "boarding": "посадка",
    "customs": "таможня",
    "passport control": "паспортный контроль",
    "excess weight": "превышение веса",
    "railway station": "жд станция",
    "carriage": "вагон",
    "make a reservation": "забронировать место"
  },
  'Кухня': {
    "fridge": "холодильник",
    "coffee pot": "кофейник",
    "cooker": "плита",
    "dishwasher": "посудомоечная машина",
    "freezer": "морозилка",
    "kettle": "чайник",
    "oven": "духовка",
    "stove": "печь",
    "toaster":	"тостер",
    "washing machine":	"стиральная машина",
    "cup": "чашка",
    "bowl": "миска",
    "crockery":	"посуда (глиняная, фаянсовая)",
    "glass": "стакан",
    "jar":	"банка",
    "jug":	"кувшин",
    "mug":	"кружка",
    "plate": "тарелка",
    "saucer": "блюдце",
    "sugar bowl": "сахарница",
    "teapot": "заварной чайник",
    "wine glass": "бокал для вина",
  },
  "Путешествия 2": {
    'luggage': 'багаж',
    'airlines': 'авиакомпания',
    'gasoline': 'бензин',
    'to take of': 'взлетать',
    'domestic tourism': 'внутренний туризм',
    'border': 'граница',
    'annual vacation': 'ежегодный отпуск',
    'railway': 'железная дорога',
    'foreign': 'иностранный',
    'ship': 'корабль',
    'map': 'карта',
    'take the waters': 'лечиться на водах',
    'arrangements': 'мероприятия',
    'route': 'маршрут',
    'island state': 'островное государство',
    'postcard': 'открытка',
    'pilgrimages to sacred places': 'паломничество по святым местам',
    'package tour': 'поездка по путевке',
    'flow of tourists': 'поток туристов',
    'streetcar': 'трамвай',
    'thermal spring': 'термальный источник'
  },
  "Математика": {
    "addition": "сложение",
    "subtraction": "вычитание",
    "multiplication": "умножение",
    "division": "деление",
    "equality": "равенство",
    "common fractions": "простые дроби",
    "decimals": "десятичные дроби",
    "percent": "процент",
    "square root": "квадратный корень",
    "squared": "в квадрате",
    "round brackets": "круглые скобки",
    "mathematics": "математика",
    "do the math": "вычислять",
    "to solve": "решать",
    "digit": "цифра",
    "number": "число",
    "odd number": "нечетное число",
    "even number": "	четное число",
    "equals to": "равно",
    "numerator": "числитель",
    "denominator": "знаменатель",
    "half": "половина",
    "quarter": "четверть",
    "to round up the numbers": "	округлять числа",
    "brackets": "квадратные скобки",
  },
  "Геометрия": {
    "point": "точка",
    "line segment": "отрезок",
    "ray": "луч",
    "line": "прямая",
    "plane shape": "геометрическая фигура",
    "solid shape": "геометрическое тело",
    "volume": "объем",
    "area": "площадь",
    "perimeter": "периметр",
    "diagonal": "диагональ",
    "size": "размер",
    "angle": "угол",
    "length": "длина",
    "width": "ширина",
    "height": "высота",
    "depths": "глубина",
    "right angle": "прямой угол",
    "obtuse angle": "тупой угол",
    "acute angle": "острый угол",
    "curved line": "кривая линия",
    "broken line": "ломаная линия",
    "parallel lines": "	параллельные линии",
    "perpendicular lines": "перпендикулярные линии",
    "radius": "радиус",
    "diameter": "диаметр",
    "vertex": "вершина",
    "edge": "ребро",
    "convex": "выпуклый",
    "concave": "вогнутый",
  },
  "Тела и фигуры": {
    "square": "квадрат",
    "circle": "круг",
    "triangle": "треугольник",
    "rectangle": "прямоугольник",
    "rhombus": "ромб",
    "trapezium": "трапеция",
    "oval": "овал",
    "cylinder": "цилиндр",
    "cube": "куб",
    "prism": "призма",
    "sphere": "сфера",
    "cone": "конус",
    "pyramid": "пирамида",
    "pentagon": "пятиугольник",
    "hexagon": "шестиугольник",
    "round": "круглый",
    "triangular": "треугольный",
    "rectangular": "прямоугольный",
    "spherical": "сферический",
  },

}
