words = {
  "Животные": {
    "wolf": "волк",
    "fox": "лиса",
    "bear": "медведь",
    "tiger": "тигр",
    "lion": "лев",
    "elephant": "слон",
    "monkey": "обезьяна",
    "camel": "верблюд",
    "rabbit": "кролик",
    "squirrel": "белка",
    "zebra": "зебра",
    "kangaroo": "кенгуру",
    "crocodile": "крокодил",
    "deer": "олень",
    "lynx": "рысь",
    "cheetah": "гепард",
    "raccoon": "енот",
    "giraffe": "жираф",
    "hedgehog": "еж",
    "anteater": "муравьед",
    "domestic animals": "домашние животные",
    "cow": "корова",
    "bull": "бык",
    "horse": "лошадь",
    "guinea pig": "морская свинка",
    "wild animal": "дикое животное"
  },
  "Еда": {
    "pear": "груша",
    "strawberry": "клубника",
    "grapes": "виноград",
    "carrot": "морковь",
    "cucumber": "огурец",
    "cabbage ": "капуста",
    "ham": "ветчина",
    "beef": "говядина",
    "pork": "свинина",
    "salmon": "семга",
    "shrimps": "креветки",
    "trout ": "форель",
    "turkey": "индейка",
    "goose": "гусь",
    "duck": "утка",
    "milkshake": "молочный коктейль",
    "soda": "газировка",
    "juice": "сок",
    "cocoa ": "какао",
    "coffee ": "кофе",
    "bread": "хлеб",
    "bun": "булка",
    "mustard": "горчица",
    "sour cream": "сметана",
    "pearl barley": "перловка"
  },
  "Основные глаголы": {
    "choose": "выбирать",
    "draw": "рисовать",
    "catch": "ловить",
    "cover": "покрывать",
    "eat ": "есть еду",
    "produce": "производить",
    "support": "поддерживать",
    "agree": "соглашаться",
    "receive": "получать",
    "break": "ломать",
    "carry": "везти",
    "develop": "развивать",
    "hope": "надеяться",
    "explain": "объяснять",
    "return": "возвращаться",
    "decide": "решать",
    "sell": "продавать",
    "pass": "миновать",
    "raise": "поднимать",
    "kill": "убивать",
    "reach": "достигать",
    "cut": "резать",
    "fall": "падать",
    "build": "строить",
    "send": "посылать",
    "buy": "покупать",
    "appear": "появляться",
    "consider": "считать",
    "remember": "помнить",
    "teach": "учить",
    "win": "побеждать",
    "walk": "идти",
    "grow": "расти",
    "spend": "тратить",
    "read": "читать",
    "speak": "говорить",
    "create": "создавать",
    "stop": "останавливать",
    "follow": "следовать",
    "watch": "смотреть",
    "understand": "понимать",
    "change": "менять",
    "learn": "учить",
    "continue": "продолжать",
    "meet": "встречать",
    "pay": "платить",
    "lose": "терять",
    "stand": "стоять",
    "sit": "сидеть",
    "write": "писать",
    "happen": "случаться",
    "believe": "верить",
    "live": "жить",
    "move": "двигаться",
    "run": "бежать",
    "play": "играть",
    "hear": "слышать",
    "help": "помогать",
    "seem": "казаться",
    "begin": "начинать",
    "keep": "хранить",
    "put": "класть",
    "leave": "оставлять",
    "become": "становиться",
    "feel": "чувствовать",
    "need": "нуждаться",
    "ask": "просить или спрашивать",
    "try": "пытаться",
    "call": "звать или звонить",
    "work": "работать",
    "tell": "рассказывать",
    "give": "давать",
    "find": "находить",
    "want": "хотеть",
    "use": "использовать",
    "see": "видеть",
    "take": "брать",
    "think": "думать",
    "know": "знать",
    "make": "делать",
    "get": "получать",
    "go": "идти",
    "say": "говорить",
    "do": "делать",
    "have": "иметь",
    "be": "быть",
  },
  "Королевский": {
    "dom+inions": "владения",
    "king": "король",
    "courtiers": "придворные",
    "empress": "императрица",
    "nobles": "дворяне",
    "queen": "королева",
    "emperor": "император",
    "troop": "войска",
    "battlement": "зубчатая стена",
    "fortress": "крепость",
    "castle": "замок",
    "kingdom": "королевство",
    "slave": "раб",
    "servant": "слуга",
    "tower": "башня",
    "valor": "доблесть",
    "crown": "корона",
    "duke": "герцог",
    "duchesses": "герцогиня",
    "regal": "царский"
  },
  "Бизнес": {
    "advantage": "превосходство",
    "advertisement": "реклама",
    "advice": "совет",
    "brand": "марка",
    "competition": "конкуренция",
    "costs": "расходы",
    "creditor": "кредитор",
    "debt": "долг",
    "deadline": "крайний срок",
    "decision": "решение",
    "employe+e": "сотрудник",
    "enq+uiry": "запрос",
    "estimate": "оценка",
    "experience": "опыт",
    "facilities": "средства",
    "feedb+ack": "обратная связь",
    "goal": "цель",
    "improvement": "улучшение",
    "+increase": "увеличение",
    "kn+owledge": "знание",
    "market": "рынок",
    "offer": "предложение",
    "pen+alty": "штраф",
    "permission": "разрешение",
    "possib+ility": "возможность",
    "profit": "прибыль",
    "refund": "возврат",
    "reminder": "напоминание",
    "responsibility": "ответственность",
    "retailer": "розничный торговец",
    "salary": "зарплата",
    "schedule": "график",
    "suggestion": "предложение",
    "wholesaler": "оптовик",
    "turnover": "оборот",
    "success ": "успех",
  },
  "Путешествия 1": {
    "traveling": "путешествие",
    "be fond of traveling": "любить путешествовать",
    "journey": "длительное путешествие",
    "school trip": "экск+урсия",
    "two-day trip": "двухдневная поездка",
    "tour": "поездка или тур",
    "package tour": "путешествие по тур. путевке",
    "cruise": "круиз",
    "flight": "полет",
    "hitch-hike": "путешествие автостопом",
    "travel agency": "туристическое агентство",
    "destination": "место назначения",
    "luggage": "багаж",
    "suitcase": "чемодан",
    "rucksack": "рюкзак",
    "porter": "носильщик",
    "information desk": "справочное бюро",
    "to arrive": "прибывать",
    "to depart": "отправляться",
    "boarding": "посадка",
    "customs": "таможня",
    "passport control": "паспортный контроль",
    "excess weight": "превышение веса",
    "railway station": "жд станция",
    "carriage": "вагон",
    "make a reservation": "забронировать место"
  },
  'Кухня': {
    "fridge": "холодильник",
    "coffee pot": "кофейник",
    "cooker": "плита",
    "dishwasher": "посудомоечная машина",
    "freezer": "морозилка",
    "kettle": "чайник",
    "oven": "духовка",
    "stove": "печь",
    "toaster":	"тостер",
    "washing machine":	"стиральная машина",
    "cup": "чашка",
    "bowl": "миска",
    "crockery":	"посуда (глиняная, фаянсовая)",
    "glass": "стакан",
    "jar":	"банка",
    "jug":	"кувшин",
    "mug":	"кружка",
    "plate": "тарелка",
    "saucer": "блюдце",
    "sugar bowl": "сахарница",
    "teapot": "заварной чайник",
    "wine glass": "бокал для вина",
  },
  "Путешествия 2": {
    'luggage': 'багаж',
    'airlines': 'авиакомпания',
    'gasoline': 'бензин',
    'to take of': 'взлетать',
    'domestic tourism': 'внутренний туризм',
    'border': 'граница',
    'annual vacation': 'ежегодный отпуск',
    'railway': 'железная дорога',
    'foreign': 'иностранный',
    'ship': 'корабль',
    'map': 'карта',
    'take the waters': 'лечиться на водах',
    'arrangements': 'мероприятия',
    'route': 'маршрут',
    'island state': 'островное государство',
    'postcard': 'открытка',
    'pilgrimages to sacred places': 'паломничество по святым местам',
    'package tour': 'поездка по путевке',
    'flow of tourists': 'поток туристов',
    'streetcar': 'трамвай',
    'thermal spring': 'термальный источник'
  },
  "Математика": {
    "addition": "сложение",
    "subtraction": "вычитание",
    "multiplication": "умножение",
    "division": "деление",
    "equality": "равенство",
    "common fractions": "простые дроби",
    "decimals": "десятичные дроби",
    "percent": "процент",
    "square root": "квадратный корень",
    "squared": "в квадрате",
    "round brackets": "круглые скобки",
    "mathematics": "математика",
    "do the math": "вычислять",
    "to solve": "решать",
    "digit": "цифра",
    "number": "число",
    "odd number": "нечетное число",
    "even number": "	четное число",
    "equals to": "равно",
    "numerator": "числитель",
    "denominator": "знаменатель",
    "half": "половина",
    "quarter": "четверть",
    "to round up the numbers": "	округлять числа",
    "brackets": "квадратные скобки",
  },
  "Геометрия": {
    "point": "точка",
    "line segment": "отрезок",
    "ray": "луч",
    "line": "прямая",
    "plane shape": "геометрическая фигура",
    "solid shape": "геометрическое тело",
    "volume": "объем",
    "area": "площадь",
    "perimeter": "периметр",
    "diagonal": "диагональ",
    "size": "размер",
    "angle": "угол",
    "length": "длина",
    "width": "ширина",
    "height": "высота",
    "depths": "глубина",
    "right angle": "прямой угол",
    "obtuse angle": "тупой угол",
    "acute angle": "острый угол",
    "curved line": "кривая линия",
    "broken line": "ломаная линия",
    "parallel lines": "	параллельные линии",
    "perpendicular lines": "перпендикулярные линии",
    "radius": "радиус",
    "diameter": "диаметр",
    "vertex": "вершина",
    "edge": "ребро",
    "convex": "выпуклый",
    "concave": "вогнутый",
  },
  "Тела и фигуры": {
    "square": "квадрат",
    "circle": "круг",
    "triangle": "треугольник",
    "rectangle": "прямоугольник",
    "rhombus": "ромб",
    "trapezium": "трапеция",
    "oval": "овал",
    "cylinder": "цилиндр",
    "cube": "куб",
    "prism": "призма",
    "sphere": "сфера",
    "cone": "конус",
    "pyramid": "пирамида",
    "pentagon": "пятиугольник",
    "hexagon": "шестиугольник",
    "round": "круглый",
    "triangular": "треугольный",
    "rectangular": "прямоугольный",
    "spherical": "сферический",
  },
  "Спортивный инвентарь": {
    "baton": "",
    "bicycle": "велосипед",
    "bowling": "боулинг",
    "cross-bar": "штанга",
    "dump-bells": "гантели",
    "flippers": "ласты",
    "goggles": "защитные очки",
    "hoop": "обруч",
    "horizontal bar": "турник",
    "jumping rope": "скакалка",
    "muffler": "боксерская перчатка",
    "racket": "ракетка",
    "roller skaters": "ролики",
    "rope": "канат",
    "simulator": "тренажер",
    "skates": "коньки",
    "skis": "лыжи",
    "stick": "клюшка",
    "stopwatch": "секундомер",
    "cue": "кий",
    "rack": "бильярдный треугольник",
    "snowboard": "сноуборд",
    "hockey stick": "хоккейная клюшка",
    "puck": "шайба",
    "luge": "сани",
    "helmet": "шлем",
    "ball": "мяч",
    "basket": "корзина",
    "goal": "ворота",
    "pin": "кегля",
    "scuba": "акваланг",
    "boat": "лодка",
    "oar": "весло",
    "sail": "парус",
  },
  "Неформальные приветствия и прощания": {
    "long time no see!": "давненько не виделись!",
    "it’s nice to have you back!": "классно, что ты вернулся!",
    "how’s life?": "как жизнь?",
    "how are things?": "как оно?",
    "how did it go?": "как все прошло?",
    "have a nice day!": "удачного дня!",
    "see you!": "увидимся!",
    "take care!": "	береги себя!",
    "talk to you later!": "поговорим позже!",
    "farewell!": "прощайте!",
    "until we meet again!": "до новых встреч!",
    "till next time!": "до следующего раза!",
    "good luck!": "удачи!",
    "sweet dreams!": "сладких снов!",
  },
  "Вводные слова": {
    "the thing is": "дело в том, что",
    "in short": "говоря кратко",
    "by the way": "	кстати",
    "if I am not mistaken": "если я не ошибаюсь",
    "look here": "послушайте",
    "first of all": "в первую очередь",
    "as a rule": "как правило",
    "in other words": "	другими словами",
    "on one hand": "с одной стороны",
    "on the other hand": "с другой стороны",
    "either way": "так или иначе",
    "as to": "	что касается",
    "as well as": "	а также",
    "as I said before": "как я говорил ранее",
    "and so forth": "	и так далее",
    "at last": "наконец",
    "all in all": "в итоге",
    "after all": "в конце концов",
  },
  "Глагольные идиомы": {
    "come first": "	прийти первым",
    "come into view": "попасть в поле зрения",
    "come to a decision": "прийти к решению",
    "do someone a favor": "	оказать кому-либо услугу",
    "do your best": "постараться",
    "do your hair": "причесаться",
    "go quiet": "притихнуть",
    "have lunch": "пообедать",
    "break a leg!": "удачи!",
    "break a promise": "нарушать обещание",
    "make a mistake": "ошибиться",
    "make money": "зарабатывать",
    "make progress": "прогрессировать",
    "take a chance": "воспользоваться шансом",
    "take a rest": "отдыхать",
    "get angry": "разозлиться",
    "get ready": "подготовиться",
    "pay respect": "выражать уважение",
    "pay someone a visit": "нанести визит",
    "pay attention to": "уделить внимание",
    "give me a break!": "С меня довольно!",
    "catch one’s breath": "перевести дух",
    "cut corners": "затягивать пояса",
  },
  'Пейзаж': {
    'forest': 'лес',
    'meadow': 'луг',
    'cloud': 'облако',
    'glade': 'поляна',
    'downhill': 'склон',
    'hilltop': 'вершина горы',
    'dawn': 'рассвет',
    'sunset': 'закат',
    'mountain': 'гора',
    'tide': 'течение',
    'river' : 'река',
    'lake': 'озеро',
    'sea': 'море',
    'ocean': 'океан',
    'coast': 'побережье',
    'beach': 'пляж',
    'sun': 'солнце',
    'moon': 'луна',
    'moonlight': 'лунный свет',
    'thaw': 'оттепель',
    'landscape': 'пейзаж'
  },
  'Морские обитатели': {
    'corals': 'кораллы',
    'fish': 'рыба',
    'trout': 'форель',
    'salmon': 'лосось',
    'swordfish': 'рыба-меч',
    'octopus': 'осьминог',
    'otter': 'выдра',
    'stingray': 'электрический скат',
    'walrus': 'морж',
    'shrimp': 'креветка',
    'frog' : 'лягушка',
    'dolphin': 'дельфин',
    'turtle': 'морская черепаха',
    'starfish': 'морская звезда',
    'shark': 'акула',
    'whale': 'кит',
    'jelly fish': 'медуза',
    'eel': 'угорь',
    'bass': 'окунь',
    'seahorse': 'морской конек',
    'mermaid': 'русалка'
  },
  'Психология': {
    'psyche': 'психика',
    'intercourse': 'взаимоотношение',
    'interaction': 'взаимнодействие',
    'hostility': 'враждебность',
    'amity': 'дружеские отношения',
    'habit': 'привычка',
    'idiosyncrasy': 'черта характера',
    'prejudice': 'предубеждение',
    'psychology': 'психология',
    'soul': 'душа',
    'psychic': 'психический',
    'mind': 'разум',
    'character': 'характер',
    'deviation': 'отклонение',
    'loony': 'сумасшедший',
    'adaptive behavior': 'адаптивное поведение',
    'abnormal personality': 'психопатия',
    'adjustment': 'приспособленность',
    'associative thinking': 'ассоциативное мышление',
    'conscience': 'совесть',
    'conditional reflex': 'условный рефлекс',
    'elicited behavior': 'реактивное поведение',
    'hysteria': 'истерия'
  },
  'Окружающая среда': {
    'animal species': 'виды животных',
    'awareness': 'осведомленность',
    'carbon dioxide': 'углекислый газ',
    'contaminant': 'загрязнитель',
    'drought': 'засуха',
    'emissions reduce': 'сокращение выбросов',
    'energy demand': 'потребность в энергии',
    'extinct species': 'вымерший вид',
    'fix the problem': 'решить проблему',
    'footprint': 'след',
    'future generations': 'будущие поколения',
    'global warming': 'глобальное потепление',
    'greenhouse gases': 'парниковые газы',
    'natural resources': 'природные ресурсы',
    'negative impact': 'негативное влияние',
    'overconsumption': 'чрезмерное потребление',
    'oxygen': 'кислород',
    'pollution': 'загрязнение',
    'population growth': 'рост населения',
    'recycling': 'переработка',
    'renewable sources': 'возобновляемые источники',
    'short term': 'в ближайшем будущем',
    'solar panels': 'солнечные панели',
    'solar power': 'солнечная энергия',
    'sustainable': 'устойчивый',
    'to be trapped': 'быть пойманным в ловушку',
    'to experience': 'испытать',
    'vulnerable': 'уязвимый',
    'wastes': 'отходы',
    'wind power': 'энергия ветра'
  },
  'Питание': {
    'absorb': 'абсорбировать, впитывать',
    'asparagus': 'спаржа',
    'bone density': 'плотность костной ткани',
    'calories': 'калории',
    'constipation': 'запор',
    'core principle': 'основной принцип',
    'dairy products': 'молочные продукты',
    'digestive problems': 'проблемы с пищеварением',
    'fibre intake': 'потребление клетчатки',
    'folic acid': 'фолиевая кислота',
    'fruit juice': 'фруктовый сок',
    'healthy eating': 'здоровое питание',
    'intake': 'прием, потребление',
    'kale': 'листовая капуста',
    'key nutrients': 'ключевые питательные вещества',
    'leafy vegetables': 'листовые овощи',
    'light dressing': 'легкая заправка (к салату)',
    'low-fat': 'с пониженным содержанием жира',
    'nourishing': 'питательный',
    'nutritional needs': 'потребности в питании',
    'obtain': 'получать, обретать',
    'portion size': 'размер порции',
    'protein': 'протеин',
    'seasonings': 'приправы',
    'skip breakfast': 'пропускать завтрак',
    'stomach acid': 'желудочная кислота',
    'unpasteurised milk': 'непастеризованное молоко',
    'vital': 'жизненно важный',
    'vitamins': 'витамины',
    'whole grain': 'цельное зерно',
  },
  "География": {
    "avalanche": "лавина",
    "azimuth": "азимут",
    "beach": "пляж",
    "border": "граница",
    "capital": "столица",
    "coastline": "береговая линия",
    "continent": "континент",
    "country": "страна",
    "degree of latitude": "градус широты",
    "degree of longitude": "градус долготы",
    "geographic coordinates": "географические координаты",
    "glacier": "ледник",
    "harbour": "бухта",
    "hill": "холм",
    "island": "остров",
    "jungle": "джунгли",
    "kilometer": "километр",
    "lake": "озеро",
    "land": "земля",
    "mountain": "гора",
    "ocean": "океан",
    "peninsula": "полуостров",
    "plain": "равнина",
    "plateau": "плато",
    "rainforest": "тропический лес",
    "region": "область",
    "river": "река",
    "sea": "море",
    "swamp": "болото",
    "time zone": "часовой пояс",
    "village": "деревня",
    "waterfall": "водопад",
    "wood": "лес",
  },
  "Космос": {
    "moon ": "луна",
    "earth ": "земля",
    "sun": "солнце",
    "venus": "Венера",
    "jupiter": "юпитер",
    "neptune": "нептун",
    "saturn": "сатурн",
    "mercury": "меркурий",
    "mars": "марс",
    "pluto": "плутон",
    "uranus": "уран",
    "astronomy": "астрономия",
    "telescope": "телескоп",
    "astronaut": "астронавт",
    "cosmonaut": "космонавт",
    "satellite": "искусственный спутник",
    "spaceship": "космический корабль",
    "rocket": "ракета",
    "alien": "инопланетянин",
    "star": "звезда",
    "constellation": "созвездие",
    "zodiac": "зодиак",
    "galaxy": "галактика",
    "universe": "вселенная",
    "comet": "комета",
    "asteroid": "астероид",
    "meteorite": "метеорит",
    "milky way": "млечный путь",
    "great bear": "большая медведица",
    "little bear": "малая медведица",
    "black hole": "черная дыра",
    "andromeda nebula": "туманность андромеды",
    "orbit": "орбита",
    "solar eclipse": "солнечное затмение",
    "lunar eclipse": "лунное затмение",
    "crater": "кратер",
    "gravity": "гравитация",
    "weightlessness state": "состояние невесомости",
    "light year": "световой год",
    "celestial bodies": "небесные тела",
    "full moon": "полнолуние",
  },
  "Образование": {
    "education": "образование",
    "upbringing": "воспитание",
    "teacher": "учитель",
    "pupil": "ученик",
    "student": "студент",
    "development": "разработка",
    "competent": "компетентный",
    "literate": "грамотный",
    "school": "школа",
    "gymnasium": "гимназия",
    "college": "колледж",
    "institute": "институт",
    "university": "университет",
    "academy": "академия",
    "conservatory": "консерватория",
    "faculty": "факультет",
    "department": "кафедра",
    "postgraduate": "аспирант",
    "course": "курс",
    "study": "учиться",
    "learn": "изучать",
    "teach": "учить",
    "syllabus": "план лекций",
    "repetition": "повторение",
    "break": "перерыв",
    "vacation": "каникулы",
    "exams": "экзамены",
    "holidays": "праздники",
    "dictionary": "словарь",
    "timetable": "расписание",
    "question": "вопрос",
    "answer": "ответ",
    "finals": "выпускные экзамены",
    "examine": "экзаменовать",
    "graduate": "выпускник",
    "expel": "отчислить",
    "diploma": "диплом",
    "classmate": "одноклассник",
    "probationer": "стажер",
    "dean": "декан",
    "principal": "ректор",
    "audience": "аудитория",
    "laboratory": "лаборатория",
    "desk": "парта",
    "blackboard": "доска"
  }
}
